### ISSUE TITLE
Missing compatibility with camunda 7.4.2 

### ISSUE THREAD

**Issue by tobiasrook** [camunda-community-hub/camunda-acm-plugin#32]
I would like to use the Plugin with camunda 7.4.2. This version wont do the job correctly. 
Thanks for your work.

[https://app.camunda.com/jira/browse/SUPPORT-2112](url)

**Comment by jangalinski** [comment]
Hi Tobias ... we cannot see your SUPPORT tickets on jira ... only camunda can. Please share the relevant parts here. Thanks. Jan

**Comment by tobiasrook** [comment]
Hello Jan,
The issue has already been forwarded to Simon. He will start working on creating usablility in the 7.4.2 version this week.

**Comment by mschoe** [comment]
Hi Simon and Jan,
has there been any progress on this?

Cheers
Michael

**Comment by jangalinski** [comment]
Not from my side, sorry ... focussing on spring-boot right now.

**Comment by mschoe** [comment]
thank you for the info.

**Comment by zambrovski** [comment]
Yes. I have a "working" version locally. 
The question was that we need a full list of non-working issues.

I'm on the spring-boot-extension right now, but would pimp the plugin afterwards. In the same time, Camunda seems to work on some ACM features....

**Comment by falko** [comment]
@zambrovski could you share you local version in a branch or so? I'd like to use it even with Camunda 7.5.
